# Generated by Django 4.2.21 on 2025-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='folder_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
